// import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import MainNavbar from "./_componentes/mainnavbar/mainnavbar";
// import "./globals.scss";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: "Anderson - Meu Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // className={`${geistSans.variable} ${geistMono.variable}`}
    <html lang="en">
      <body>
        <MainNavbar />
        {children}
      </body>
    </html>
  );
}
